apiVersion: apps/v1
kind: Deployment
metadata:
  name: show-catalog-service
  labels:
    app: show-catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: show-catalog-service
  template:
    metadata:
      labels:
        app: show-catalog-service
    spec:
      containers:
        - name: show-catalog-service
          image: suryadasari31/show-catalog-service:1.0.1
          ports:
            - containerPort: 8080
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false

